version: "3.9"
services:
  main:
    build:
      context: ./banking-dispute-backend
    command: python main.py
    ports:
      - "8000:8000"
  mcp:
    build:
      context: ./mcp-server
    command: python mcp_server.py
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./banking-dispute-frontend
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:8000
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
    ports:
      - "4173:4173"