version: "3.9"
services:
  main:
    build:
      context: ./banking-dispute-backend
    command: python app/main.py
    ports:
      - "8000:8000"
  mcp:
    build:
      context: ./banking-dispute-backend
    command: python mcp-server/mcp_server.py
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./banking-dispute-frontend
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
    ports:
      - "4173:4173"
